### ISSUE TITLE
`trace_funs` fails 

### ISSUE THREAD

**Issue by TylerGrantSmith** [moodymudskipper/ggfail#1]
```
library(ggplot2)
ggfail::trace_funs()
#> Error in methods::.TraceWithMethods(function (mapping = NULL, data = NULL, : argument 'what' should be the name of a function
```

**Comment by moodymudskipper** [comment]
Thanks, I cannot reproduce this, could you print the output of : 

```
traceback()
sessionInfo()
```

right after you get the error ?

**Comment by moodymudskipper** [comment]
oh wait, I could reproduce, my local installation wasn't synced, silly me

**Comment by TylerGrantSmith** [comment]
Why not just `suppressMessages(
        trace(fun, tracer = tracer, print = FALSE))` ?  Making that change, and a similar change in `untrace_funs` seems to get it to work for me.

``` r
library(ggplot2)
ggfail::trace_funs()
plt <- function() {
  ggplot(cars, aes(speed, dist)) +
    geom_point()
}
plt()
```

![](https://i.imgur.com/rneJ8vV.png)

``` r

plt <- function() {
  ggplot(cars, aes(speed, dist))
    geom_point()
}
plt()
#> Error in eval(expr, p): Did you forget a `+` in a ggplot call ?
#> Use `print(geom_point())` to view the object, or set `options(ggfail = FALSE)` to disable this error.
ggfail::untrace_funs()
plt()
#> geom_point: na.rm = FALSE
#> stat_identity: na.rm = FALSE
#> position_identity
```

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moodymudskipper** [comment]
Because trace() is meant to receive a name as a first argument, which i failed to do in the version I've pushed.
I believe in your version your code might not be doing what you think it does, see : https://r.789695.n4.nabble.com/trace-creates-object-in-base-namespace-if-called-on-function-argument-td4765375.html#a4765401 

it's now corrected and pushed, can you test ?

**Comment by TylerGrantSmith** [comment]
That seems to have fixed it.

**Comment by moodymudskipper** [comment]
awesome, thanks for the report!

**Comment by TylerGrantSmith** [comment]
This also works if the functions are explicitly scoped without first attaching.

``` r
ggfail::trace_funs()
plt <- function() {
  ggplot2::ggplot(cars, aes(speed, dist))
    ggplot2::geom_point()
}
plt()
#> Error in eval(expr, p): Did you forget a `+` in a ggplot call ?
#> Use `print(ggplot2::geom_point())` to view the object, or set `options(ggfail = FALSE)` to disable this error.
```

<sup>Created on 2020-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by moodymudskipper** [comment]
Ah, interesting, it makes sense, the namespace of ggplot2 is loaded when running the first trace call, and `ggplot2::geom_point()` is traced when you call it.

**Comment by TylerGrantSmith** [comment]
It is actually loaded when you call `getNamespaceExports`.

**Comment by moodymudskipper** [comment]
right
